"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Se lee de la variable de entorno SECRET_KEY (ver .env). El default solo es
# un fallback de desarrollo.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-j0^=%g8(^3zui4$d9u4eal58#t9f=*d7_bc$^c03yo4!i&k(ol'
)

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG es False salvo que la env DEBUG sea "true"/"1"/"yes".
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('1', 'true', 'yes', 'on')

# Helper: convierte "a,b,c" (env) en lista, ignorando vacíos.
def _env_list(name, default):
    return [x.strip() for x in os.environ.get(name, default).split(',') if x.strip()]

# Hosts permitidos (separados por coma en la env ALLOWED_HOSTS).
ALLOWED_HOSTS = _env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1')

# Puerto público del sitio (nginx). Las orígenes CORS/CSRF se derivan de aquí
# para no repetir el puerto en el .env: cambiar WEB_PORT basta. En producción
# se sobreescriben poniendo CORS_ALLOWED_ORIGINS/CSRF_TRUSTED_ORIGINS al dominio real.
WEB_PORT = os.environ.get('WEB_PORT', '8090')
_DEFAULT_WEB_ORIGINS = f'http://localhost:{WEB_PORT},http://127.0.0.1:{WEB_PORT}'

# Orígenes confiables para CSRF (admin de Django). Deben incluir esquema y puerto.
CSRF_TRUSTED_ORIGINS = _env_list('CSRF_TRUSTED_ORIGINS', _DEFAULT_WEB_ORIGINS)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'shop',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise sirve los estáticos (admin/DRF) con DEBUG=False, justo tras SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'ecommerce_db'),
        'USER': os.environ.get('POSTGRES_USER', 'ecommerce_user'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'ecommerce_pass'),
        'HOST': os.environ.get('POSTGRES_HOST', 'postgres'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        # search_path: las tablas del negocio (product/category/Inventory) viven en
        # `tienda`; los modelos managed=False las resuelven sin qualificar. Django
        # crea/gestiona sus tablas (auth, sesiones, cart, cart_item) en `public`,
        # que va primero en el path (las nuevas tablas managed=True caen ahí).
        'OPTIONS': {
            'options': '-c search_path=public,tienda'
        },
    }
}

# CORS: orígenes permitidos (separados por coma en la env CORS_ALLOWED_ORIGINS).
# El frontend propio usa mismo-origen (nginx), así que esto solo aplica a
# clientes externos autorizados.
CORS_ALLOWED_ORIGINS = _env_list('CORS_ALLOWED_ORIGINS', _DEFAULT_WEB_ORIGINS)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    # Límite de peticiones por IP (anónimos) y por usuario. El scope 'login'
    # se aplica explícitamente en la vista de login (anti fuerza bruta).
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '200/min',
        'user': '400/min',
        'login': '5/min',
    },
    # Paginación opcional: sin ?limit= devuelve la lista completa (no rompe el
    # front actual); los clientes pueden pedir ?limit=&offset= cuando quieran.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
}

# Número de WhatsApp para el checkout (configurable por env).
WHATSAPP_PHONE = os.environ.get('WHATSAPP_PHONE', '51923949691')

# Tipo de negocio: 'variants' (ropa: talla/color) o 'simple' (cosméticos: producto único).
# Lo expone /api/config/ para que el frontend estático sepa qué mostrar.
STORE_TYPE = os.environ.get('STORE_TYPE', 'simple')

# Evolution API (para que el panel admin envíe mensajes de WhatsApp).
EVOLUTION_API_URL = os.environ.get('EVOLUTION_API_URL', 'http://evolution-api:8080')
EVOLUTION_API_KEY = os.environ.get('EVOLUTION_API_KEY', '123456.+az1')
EVOLUTION_INSTANCE = os.environ.get('EVOLUTION_INSTANCE', 'test')

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Zona horaria local de la tienda (Perú, UTC-5 fijo, sin horario de verano).
# Con USE_TZ=False Django trabaja en hora local naïve: las fechas se guardan y se
# devuelven en esta zona, en línea con la del servidor Postgres (timezone=TZ).
TIME_ZONE = os.environ.get('TZ', 'America/Lima')

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/app/staticfiles'

# WhiteNoise: almacenamiento comprimido para estáticos (sirve con DEBUG=False).
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = '/app/media'
