-- ============================================================
--  Schema `tienda`: dominio del negocio (e-commerce + bot unidos).
--  Aquí viven catálogo, inventario y órdenes. El framework Django
--  (auth, sesiones, cart, cart_item) se queda en `public`.
--  Las órdenes (antes la tabla muerta `sale`) ahora son tienda.orders
--  (ver 02_bot_schema.sql), para que cualquier canal de venta pueda
--  tocar el inventario sin FKs cruzados entre schemas.
-- ============================================================

CREATE SCHEMA IF NOT EXISTS tienda;

-- Kardex: libro de movimientos de inventario. Cada fila es un movimiento; el
-- stock actual (product.stock / product_variant.stock) lo mantiene un trigger
-- desde aquí (ver 04_inventory.sql). Movimientos inmutables (append-only).
CREATE TABLE tienda."Inventory" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "id_product" bigint NOT NULL,
  "id_variant" bigint,                       -- movimiento por variante (ropa) o NULL
  "movement_type" character varying(20) NOT NULL,  -- INGRESO, AJUSTE, MERMA, DEVOLUCION, VENTA
  "quantity" integer NOT NULL,               -- delta con signo (+entra, -sale)
  "unit_cost" numeric(10,2),                 -- costo en INGRESO (valorización) / precio de venta en VENTA (solo display)
  "note" text,
  PRIMARY KEY ("id")
);

CREATE TABLE tienda."category" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "category_name" character varying,
  PRIMARY KEY ("id")
);

CREATE TABLE tienda."product" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "product_name" character varying,
  "details" text,
  "id_category" bigint,
  "price_retail" bigint,      -- precio por menor / precio normal (precio principal)
  "price_wholesale" bigint,   -- precio por mayor (ropa) / con descuento (cosméticos); NULL si no aplica
  "stock" integer NOT NULL DEFAULT 0,  -- stock simple (se usa cuando el producto NO tiene variantes); lo mantiene el trigger de Inventory
  "cost" numeric(10,2),       -- costo unitario actual (para valorización del inventario); lo setea el último INGRESO
  "image" character varying,
  PRIMARY KEY ("id")
);

-- Variantes de producto (talla/color con stock propio). Solo las usa el cliente
-- de productos con variantes (ropa); en cosméticos esta tabla queda vacía y el
-- stock vive en product.stock. Los precios NO viven aquí (heredan de product).
CREATE TABLE tienda."product_variant" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_product" bigint,
  "size" character varying(50),   -- talla (NULL si no aplica)
  "color" character varying(50),  -- color (NULL si no aplica)
  "stock" integer NOT NULL DEFAULT 0,
  "sku" character varying(100),
  "created_at" timestamp NOT NULL DEFAULT (now()),
  PRIMARY KEY ("id"),
  UNIQUE ("id_product", "size", "color")
);

ALTER TABLE tienda."Inventory" ADD CONSTRAINT "Inventory_id_product_fkey" FOREIGN KEY ("id_product") REFERENCES tienda."product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE tienda."Inventory" ADD CONSTRAINT "Inventory_id_variant_fkey" FOREIGN KEY ("id_variant") REFERENCES tienda."product_variant" ("id") ON DELETE CASCADE;

ALTER TABLE tienda."product" ADD CONSTRAINT "product_id_category_fkey" FOREIGN KEY ("id_category") REFERENCES tienda."category" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE tienda."product_variant" ADD CONSTRAINT "product_variant_id_product_fkey" FOREIGN KEY ("id_product") REFERENCES tienda."product" ("id") ON DELETE CASCADE;
