CREATE TABLE "Inventory" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "id_product" bigint,
  "type" smallint NOT NULL,
  "amount" bigint,
  PRIMARY KEY ("id")
);

CREATE TABLE "category" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "category_name" character varying,
  PRIMARY KEY ("id")
);

CREATE TABLE "product" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "product_name" character varying,
  "details" text,
  "id_category" bigint,
  "price" bigint,
  "image" character varying,
  PRIMARY KEY ("id")
);

CREATE TABLE "sale" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "id_product" bigint,
  "product_name" character varying,
  "unit_price" numeric,
  "amount" numeric,
  "total_price" numeric,
  PRIMARY KEY ("id")
);

ALTER TABLE "Inventory" ADD CONSTRAINT "Inventory_id_product_fkey" FOREIGN KEY ("id_product") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product" ADD CONSTRAINT "product_id_category_fkey" FOREIGN KEY ("id_category") REFERENCES "category" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sale" ADD CONSTRAINT "sale_id_product_fkey" FOREIGN KEY ("id_product") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;
